# Generated by Django 3.1.5 on 2021-02-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pro_descripcion',
            field=models.TextField(null=True),
        ),
    ]
