# Generated by Django 3.1.5 on 2021-02-12 23:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('PRINCIPAL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blg_id', models.AutoField(primary_key=True, serialize=False)),
                ('blg_tipo', models.CharField(choices=[('R', 'RECETAS'), ('N', 'NOTICIAS')], max_length=1)),
                ('blg_titulo', models.CharField(max_length=32)),
                ('blg_descripcion', models.CharField(max_length=256)),
                ('blg_banner', models.ImageField(max_length=256, upload_to='principal/blog/')),
                ('blg_video', models.URLField()),
                ('blg_post', tinymce.models.HTMLField()),
                ('blg_fecha_post', models.DateTimeField(auto_now_add=True)),
                ('blg_fecha_act', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
